### ISSUE TITLE
Change the folder name to unix friendly environment.

### ISSUE THREAD

**Issue by s-r-aman** [syntax-cbpgec/Scobotics#1]
Currently, the folders are a mix of lowercase and uppercase and with some with inconsistencies. It would be great if it can be changed to a Unix friendly environment like `object_avoiding_robot`.

**Comment by s-r-aman** [comment]
If you say I will do it. @Rawkush

**Comment by Rawkush** [comment]
If you think it's a good idea, go ahead

**Comment by s-r-aman** [comment]
Hey @Rawkush! I have done the second folder renaming. But I am unable to rename the `Line_Following_robot` to `line_following_robot`.

**Comment by s-r-aman** [comment]
This is a gotcha! Read [Why git is failing to detect folder renames](https://stackoverflow.com/a/37470090). Since I am just changing case.

**Comment by Rawkush** [comment]
I will do it then

**Comment by s-r-aman** [comment]
Done.

**Comment by Rawkush** [comment]
Okay

**Comment by s-r-aman** [comment]
I am closing.
